export const AD_LIMITS = {
    MIN_IMAGES: 1,
    MAX_IMAGES: 6,
    MAX_IMAGE_BYTES: 5 * 1024 * 1024,
    MIN_TITLE_CHARS: 10,
    MAX_TITLE_CHARS: 60,
    MIN_DESCRIPTION_CHARS: 20,
    MAX_DESCRIPTION_CHARS: 500,
    MAX_SPARE_PARTS: 20,
} as const;

export const MIN_AD_IMAGES = AD_LIMITS.MIN_IMAGES;
export const MAX_AD_IMAGES = AD_LIMITS.MAX_IMAGES;
export const MAX_AD_IMAGE_BYTES = AD_LIMITS.MAX_IMAGE_BYTES;
export const MIN_AD_TITLE_CHARS = AD_LIMITS.MIN_TITLE_CHARS;
export const MAX_AD_TITLE_CHARS = AD_LIMITS.MAX_TITLE_CHARS;
export const MIN_AD_DESCRIPTION_CHARS = AD_LIMITS.MIN_DESCRIPTION_CHARS;
export const MAX_AD_DESCRIPTION_CHARS = AD_LIMITS.MAX_DESCRIPTION_CHARS;
export const MAX_AD_SPARE_PARTS = AD_LIMITS.MAX_SPARE_PARTS;
