#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { Validation, runStandalone, ROOT } = require('./shared');

const META = { id: 'LOCK-001', name: 'Lockfile Validation', version: '1.0.0', category: 'Dependencies' };

function run(val) {
  const lockfilePath = path.join(ROOT, 'package-lock.json');

  if (!fs.existsSync(lockfilePath)) {
    val.error('package-lock.json not found. Run npm install.');
    return;
  }

  const lockfile = JSON.parse(fs.readFileSync(lockfilePath, 'utf-8'));

  if (lockfile.lockfileVersion !== 3) {
    val.error(`Expected lockfileVersion 3, got ${lockfile.lockfileVersion}. Use npm v10+.`);
  }

  const rootPkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf-8'));
  const expectedManager = rootPkg.packageManager || 'npm@10.9.7';
  const lockPkgMgr = lockfile.packages?.['']?.packageManager;
  if (lockPkgMgr && lockPkgMgr !== expectedManager) {
    val.error(`Lockfile generated by ${lockPkgMgr}, expected ${expectedManager}.`);
  }

  const lockRoot = lockfile.packages?.[''] || {};
  if (rootPkg.workspaces) {
    const sortedRoot = [...rootPkg.workspaces].sort();
    const sortedLock = [...(lockRoot.workspaces || [])].sort();
    if (JSON.stringify(sortedRoot) !== JSON.stringify(sortedLock)) {
      val.error('Lockfile workspace entries mismatch. Run npm install.');
    }
  }

  const stagedFiles = (() => {
    try {
      const out = execSync('git diff --cached --name-only', { cwd: ROOT, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] });
      return out.split('\n').filter(Boolean);
    } catch { return []; }
  })();

  const anyPkgJsonChanged = stagedFiles.some(f => path.basename(f) === 'package.json');
  const lockfileChanged = stagedFiles.some(f => path.basename(f) === 'package-lock.json');

  if (anyPkgJsonChanged && !lockfileChanged) {
    val.warning('package.json changed but package-lock.json unchanged. Run npm install.');
  }

  if (!anyPkgJsonChanged && lockfileChanged) {
    val.warning('package-lock.json changed but no package.json changed. Possible manual edit.');
  }

  try {
    execSync('npm install --package-lock-only --ignore-scripts --no-audit --no-fund', {
      cwd: ROOT,
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
      timeout: 60000,
    });
  } catch (e) {
    val.error(`npm install --package-lock-only failed: ${e.stderr || e.message}`);
    return;
  }

  try {
    execSync('git diff --exit-code package-lock.json', {
      cwd: ROOT,
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
  } catch {
    val.error('package-lock.json is inconsistent. Run npm install to update it.');
  }

  const depKeys = new Set();
  const lockPkgs = lockfile.packages || {};
  for (const [key, val_] of Object.entries(lockPkgs)) {
    if (key === '' || val_.link === true) continue;
    const depKey = `${key}@${val_.version || 'unknown'}`;
    if (depKeys.has(depKey)) {
      val.error(`Duplicate version entry in lockfile: ${depKey}`);
    }
    depKeys.add(depKey);
  }
}

if (require.main === module) {
  runStandalone(META, run);
}
module.exports = { meta: META, run };
